// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
            "DefaultFirebaseOptions have not been configured");
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
            "DefaultFirebaseOptions have not been configured");
      case TargetPlatform.windows:
        throw UnsupportedError(
            "DefaultFirebaseOptions have not been configured");
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRnmFt7KLbTPwAvYeFYaUdaElSSFmN4EY',
    appId: '1:88468625362:web:8975cd9c51631ef973da0b',
    messagingSenderId: '88468625362',
    projectId: 'weather-blanket',
    authDomain: 'weather-blanket.firebaseapp.com',
    storageBucket: 'weather-blanket.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrs3yIagams5Yi9sZdu5TcC5ZOFh1LPgA',
    appId: '1:88468625362:ios:3bda3cb18d6df9ae73da0b',
    messagingSenderId: '88468625362',
    projectId: 'weather-blanket',
    storageBucket: 'weather-blanket.firebasestorage.app',
    iosClientId: '88468625362-oglgitob2t4ps7odps9uhk05scttst0b.apps.googleusercontent.com',
    iosBundleId: 'app.tempestry',
  );

}